# fly.toml app configuration file generated for mindmeld on 2024-09-20T17:43:21+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'mindmeld'
primary_region = 'cdg'

[build]

[env]
  BACKEND_URL = 'https://mindmeld.fly.dev'
  PORT = 3000
  FRONTEND_URL = 'https://mindmeldtool.netlify.app'
  NODE_ENV = 'production'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
